Remove spaces from modbus request variable names
Variable names with spaces caused crash when disabling a request after reaching the crash threshold
with:
```
FuzzowskiRuntimeError(f'Invalid path name: {path_name}')
fuzzowski.exception.FuzzowskiRuntimeError: Invalid path name: read_holding_registers.start address
```